version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: restaurant_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Tamare27!
      MYSQL_DATABASE: restaurant
      MYSQL_USER: derek13
      MYSQL_PASSWORD: Tamare27!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
